# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

#!/bin/zsh
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

# Zsh options.
#setopt extended_glob

# Autoload functions you might want to use with antidote.
#ZFUNCDIR=${ZFUNCDIR:-$ZDOTDIR/functions}
#fpath=($ZFUNCDIR $fpath)
#autoload -Uz $fpath[1]/*(.:t)

# Source zstyles you might use with antidote.
#[[ -e ${ZDOTDIR:-~}/.zstyles ]] && source ${ZDOTDIR:-~}/.zstyles

# Clone antidote if necessary.
#[[ -d ${ZDOTDIR:-~}/.antidote ]] ||
#  git clone https://github.com/mattmc3/antidote ${ZDOTDIR:-~}/.antidote

# Create an amazing Zsh config using antidote plugins.
#source ${ZDOTDIR:-~}/.antidote/antidote.zsh
#antidote load

#set -o emacs
#alias rm="rm -i"
#PATH=/opt/homebrew/bin/:HOME/.local/bin:/opt/local/bin:/Users/micah/Library/Python/3.9/bin:/usr/sbin:/sbin:$PATH



#autoload -Uz bracketed-paste-magic
#zle -N bracketed-paste bracketed-paste-magic

#autoload -Uz url-quote-magic
#zle -N self-insert url-quote-magic

#WINEFSYNC=1
#WINEESYNC=1

#HOMEBREW_NO_ANALYTICS=1

#SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#alias switch="darwin-rebuild switch --flake ~/git/nix-infra/home-manager/clients"
