version: '3.8'

services:
  jellyfin:
    image: docker.io/linuxserver/jellyfin:latest
    ports:
      - "8096:8096"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - "jellyfin:/config"
      - "$MOVIES_DIR:/movies"
      - "$TV_DIR:/tv"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

volumes:
  jellyfin: