{ modulesPath, ... }:
{

  # This file is normally generated by nixos-infect. Don't use it as-is -- import the generated file in /etc/nixos/hardware-configuration.nix.

  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
  boot.loader.grub = {
    efiSupport = true;
    efiInstallAsRemovable = true;

    configurationLimit = 1;
    device = "nodev";
  };
  boot.loader.efi.canTouchEfiVariables = false;
  networking.hostId = "7f4a3c1d";
  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "xen_blkfront" ];
  boot.initrd.kernelModules = [ "nvme" ];
  
}
