#cloud-config

# Add your SSH key for the default user
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHFQy6Jw3QC3ADSbNdRZZSTZMOwB7o/+SQatG4Er2gtC micah@haruka.tail8d76a.ts.net
 
# Replace root's authorized_keys with your SSH key
write_files:
  - path: /root/.ssh/authorized_keys
    content: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHFQy6Jw3QC3ADSbNdRZZSTZMOwB7o/+SQatG4Er2gtC micah@haruka.tail8d76a.ts.net 
    owner: root:root
    permissions: '0600'

# Update packages and install git and curl
packages:
  - git
  - curl

# Run the nixos-infect script
runcmd:
  - curl -fsSL https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | NIX_CHANNEL=nixos-23.05 bash -x 
